import AndroidSwitch from '../utilities/AndroidSwitch'
import InputFieldSetup from './InputFieldSetup'

export default function CategoryConfigRow({ config, index, setChange, loading, error }) {
  return (
    <tr>
      <td>{index + 1}</td>
      <td>{config?.category?.name}</td>
      <td>
        <InputFieldSetup
          val={config?.saving_acc_reg_fee}
          name="saving_acc_reg_fee"
          index={index}
          setChange={setChange}
          disabled={loading}
          error={error?.saving_acc_reg_fee}
        />
      </td>
      <td>
        <InputFieldSetup
          val={config?.saving_acc_closing_fee}
          name="saving_acc_closing_fee"
          index={index}
          setChange={setChange}
          disabled={loading}
          error={error?.saving_acc_closing_fee}
        />
      </td>
      <td>
        <InputFieldSetup
          val={config?.loan_acc_reg_fee}
          name="loan_acc_reg_fee"
          index={index}
          setChange={setChange}
          disabled={loading}
          error={error?.loan_acc_reg_fee}
        />
      </td>
      <td>
        <InputFieldSetup
          val={config?.loan_acc_closing_fee}
          name="loan_acc_closing_fee"
          index={index}
          setChange={setChange}
          disabled={loading}
          error={error?.loan_acc_closing_fee}
        />
      </td>
      <td>
        <InputFieldSetup
          val={config?.saving_withdrawal_fee}
          name="saving_withdrawal_fee"
          index={index}
          setChange={setChange}
          disabled={loading}
          error={error?.saving_withdrawal_fee}
        />
      </td>
      <td>
        <InputFieldSetup
          val={config?.loan_saving_withdrawal_fee}
          name="loan_saving_withdrawal_fee"
          index={index}
          setChange={setChange}
          disabled={loading}
          error={error?.loan_saving_withdrawal_fee}
        />
      </td>
      <td>
        <InputFieldSetup
          val={config?.min_saving_withdrawal}
          name="min_saving_withdrawal"
          index={index}
          setChange={setChange}
          disabled={loading}
          error={error?.min_saving_withdrawal}
        />
      </td>
      <td>
        <InputFieldSetup
          val={config?.max_saving_withdrawal}
          name="max_saving_withdrawal"
          index={index}
          setChange={setChange}
          disabled={loading}
          error={error?.max_saving_withdrawal}
        />
      </td>
      <td>
        <InputFieldSetup
          val={config?.min_loan_saving_withdrawal}
          name="min_loan_saving_withdrawal"
          index={index}
          setChange={setChange}
          disabled={loading}
          error={error?.min_loan_saving_withdrawal}
        />
      </td>
      <td>
        <InputFieldSetup
          val={config?.max_loan_saving_withdrawal}
          name="max_loan_saving_withdrawal"
          index={index}
          setChange={setChange}
          disabled={loading}
          error={error?.max_loan_saving_withdrawal}
        />
      </td>
      <td>
        <InputFieldSetup
          val={config?.saving_acc_check_time_period}
          name="saving_acc_check_time_period"
          index={index}
          setChange={setChange}
          disabled={loading}
          error={error?.saving_acc_check_time_period}
        />
      </td>
      <td>
        <InputFieldSetup
          val={config?.loan_acc_check_time_period}
          name="loan_acc_check_time_period"
          index={index}
          setChange={setChange}
          disabled={loading}
          error={error?.loan_acc_check_time_period}
        />
      </td>
      <td>
        <AndroidSwitch
          value={config?.disable_unchecked_saving_acc}
          toggleStatus={(e) => setChange(e.target.checked, 'disable_unchecked_saving_acc', index)}
        />
      </td>
      <td>
        <AndroidSwitch
          value={config?.disable_unchecked_loan_acc}
          toggleStatus={(e) => setChange(e.target.checked, 'disable_unchecked_loan_acc', index)}
        />
      </td>
      <td>
        <InputFieldSetup
          val={config?.inactive_saving_acc_disable_time_period}
          name="inactive_saving_acc_disable_time_period"
          index={index}
          setChange={setChange}
          disabled={loading}
          error={error?.inactive_saving_acc_disable_time_period}
        />
      </td>
      <td>
        <InputFieldSetup
          val={config?.inactive_loan_acc_disable_time_period}
          name="inactive_loan_acc_disable_time_period"
          index={index}
          setChange={setChange}
          disabled={loading}
          error={error?.inactive_loan_acc_disable_time_period}
        />
      </td>
    </tr>
  )
}
