export const en_police_stations = () => [
  'Amtali',
  'Bamna',
  'Barguna Sadar',
  'Betagi',
  'Patharghata',
  'Taltali',
  'Muladi',
  'Babuganj',
  'Agailjhara',
  'Barisal Sadar',
  'Bakerganj',
  'Banaripara',
  'Gaurnadi',
  'Hizla',
  'Mehendiganj',
  'Wazirpur',
  'Bhola Sadar',
  'Burhanuddin',
  'Char Fasson',
  'Daulatkhan',
  'Lalmohan',
  'Manpura',
  'Tazumuddin',
  'Jhalokati Sadar',
  'Kathalia',
  'Nalchity',
  'Rajapur',
  'Bauphal',
  'Dashmina',
  'Galachipa',
  'Kalapara',
  'Mirzaganj',
  'Patuakhali Sadar',
  'Dumki',
  'Rangabali',
  'Bhandaria',
  'Mathbaria',
  'Nazirpur',
  'Nesarabad',
  'Pirojpur Sadar',
  'Zianagar',
  'Bandarban Sadar',
  'Thanchi',
  'Lama',
  'Naikhongchhari',
  'Ali kadam',
  'Rowangchhari',
  'Ruma',
  'Brahmanbaria Sadar',
  'Ashuganj',
  'Nasirnagar',
  'Nabinagar',
  'Sarail',
  'Shahbazpur Town',
  'Kasba',
  'Akhaura',
  'Bancharampur',
  'Bijoynagar',
  'Chandpur Sadar',
  'Faridganj',
  'Haimchar',
  'Haziganj',
  'Kachua',
  'Matlab Uttar',
  'Matlab Dakkhin',
  'Shahrasti',
  'Anwara',
  'Banshkhali',
  'Boalkhali',
  'Chandanaish',
  'Fatikchhari',
  'Hathazari',
  'Lohagara',
  'Mirsharai',
  'Patiya',
  'Rangunia',
  'Raozan',
  'Sandwip',
  'Satkania',
  'Sitakunda',
  'Barura',
  'Brahmanpara',
  'Burichong',
  'Chandina',
  'Chauddagram',
  'Daudkandi',
  'Debidwar',
  'Homna',
  'Comilla Sadar',
  'Laksam',
  'Monohorgonj',
  'Meghna',
  'Muradnagar',
  'Nangalkot',
  'Comilla Sadar South',
  'Titas',
  'Chakaria',
  "{{198}}''{{199}}",
  'Kutubdia',
  'Maheshkhali',
  'Ramu',
  'Teknaf',
  'Ukhia',
  'Pekua',
  'Feni Sadar',
  'Chagalnaiya',
  'Daganbhyan',
  'Parshuram',
  'Fhulgazi',
  'Sonagazi',
  'Dighinala',
  'Khagrachhari',
  'Lakshmichhari',
  'Mahalchhari',
  'Manikchhari',
  'Matiranga',
  'Panchhari',
  'Ramgarh',
  'Lakshmipur Sadar',
  'Raipur',
  'Ramganj',
  'Ramgati',
  'Komol Nagar',
  'Noakhali Sadar',
  'Begumganj',
  'Chatkhil',
  'Companyganj',
  'Shenbag',
  'Hatia',
  'Kobirhat',
  'Sonaimuri',
  'Suborno Char',
  'Rangamati Sadar',
  'Belaichhari',
  'Bagaichhari',
  'Barkal',
  'Juraichhari',
  'Rajasthali',
  'Kaptai',
  'Langadu',
  'Nannerchar',
  'Kaukhali',
  'Dhamrai',
  'Dohar',
  'Keraniganj',
  'Nawabganj',
  'Savar',
  'Faridpur Sadar',
  'Boalmari',
  'Alfadanga',
  'Madhukhali',
  'Bhanga',
  'Nagarkanda',
  'Charbhadrasan',
  'Sadarpur',
  'Shaltha',
  'Gazipur Sadar-Joydebpur',
  'Kaliakior',
  'Kapasia',
  'Sripur',
  'Kaliganj',
  'Tongi',
  'Gopalganj Sadar',
  'Kashiani',
  'Kotalipara',
  'Muksudpur',
  'Tungipara',
  'Dewanganj',
  'Baksiganj',
  'Islampur',
  'Jamalpur Sadar',
  'Madarganj',
  'Melandaha',
  'Sarishabari',
  'Narundi Police I.C',
  'Astagram',
  'Bajitpur',
  'Bhairab',
  'Hossainpur',
  'Itna',
  'Karimganj',
  'Katiadi',
  'Kishoreganj Sadar',
  'Kuliarchar',
  'Mithamain',
  'Nikli',
  'Pakundia',
  'Tarail',
  'Madaripur Sadar',
  'Kalkini',
  'Rajoir',
  'Shibchar',
  'Manikganj Sadar',
  'Singair',
  'Shibalaya',
  'Saturia',
  'Harirampur',
  'Ghior',
  'Lohajang',
  'Sreenagar',
  'Munshiganj Sadar',
  'Sirajdikhan',
  'Tongibari',
  'Gazaria',
  'Bhaluka',
  'Trishal',
  'Haluaghat',
  'Muktagachha',
  'Dhobaura',
  'Fulbaria',
  'Gaffargaon',
  'Gauripur',
  'Ishwarganj',
  'Mymensingh Sadar',
  'Nandail',
  'Phulpur',
  'Araihazar',
  'Sonargaon',
  'Bandar',
  'Naryanganj Sadar',
  'Rupganj',
  'Siddirgonj',
  'Belabo',
  'Monohardi',
  'Narsingdi Sadar',
  'Palash',
  'Raipura, Narsingdi',
  'Shibpur',
  'Kendua Upazilla',
  'Atpara Upazilla',
  'Barhatta Upazilla',
  'Durgapur Upazilla',
  'Kalmakanda Upazilla',
  'Madan Upazilla',
  'Mohanganj Upazilla',
  'Netrakona-S Upazilla',
  'Purbadhala Upazilla',
  'Khaliajuri Upazilla',
  'Baliakandi',
  'Goalandaghat',
  'Pangsha',
  'Kalukhali',
  'Rajbari Sadar',
  'Shariatpur Sadar -Palong',
  'Damudya',
  'Naria',
  'Jajira',
  'Bhedarganj',
  'Gosairhat',
  'Jhenaigati',
  'Nakla',
  'Nalitabari',
  'Sherpur Sadar',
  'Sreebardi',
  'Tangail Sadar',
  'Sakhipur',
  'Basail',
  'Madhupur',
  'Ghatail',
  'Kalihati',
  'Nagarpur',
  'Mirzapur',
  'Gopalpur',
  'Delduar',
  'Bhuapur',
  'Dhanbari',
  'Bagerhat Sadar',
  'Chitalmari',
  'Fakirhat',
  'Mollahat',
  'Mongla',
  'Morrelganj',
  'Rampal',
  'Sarankhola',
  'Damurhuda',
  'Chuadanga-S',
  'Jibannagar',
  'Alamdanga',
  'Abhaynagar',
  'Keshabpur',
  'Bagherpara',
  'Jessore Sadar',
  'Chaugachha',
  'Manirampur',
  'Jhikargachha',
  'Sharsha',
  'Jhenaidah Sadar',
  'Maheshpur',
  'Kotchandpur',
  'Shailkupa',
  'Harinakunda',
  'Terokhada',
  'Batiaghata',
  'Dacope',
  'Dumuria',
  'Dighalia',
  'Koyra',
  'Paikgachha',
  'Phultala',
  'Rupsa',
  'Kushtia Sadar',
  'Kumarkhali',
  'Daulatpur',
  'Mirpur',
  'Bheramara',
  'Khoksa',
  'Magura Sadar',
  'Mohammadpur',
  'Shalikha',
  'Sreepur',
  'angni',
  'Mujib Nagar',
  'Meherpur-S',
  'Narail-S Upazilla',
  'Lohagara Upazilla',
  'Kalia Upazilla',
  'Satkhira Sadar',
  'Assasuni',
  'Debhata',
  'Tala',
  'Kalaroa',
  'Shyamnagar',
  'Adamdighi',
  'Bogra Sadar',
  'Sherpur',
  'Dhunat',
  'Dhupchanchia',
  'Gabtali',
  'Kahaloo',
  'Nandigram',
  'Sahajanpur',
  'Sariakandi',
  'Shibganj',
  'Sonatala',
  'Joypurhat S',
  'Akkelpur',
  'Kalai',
  'Khetlal',
  'Panchbibi',
  'Naogaon Sadar',
  'Mohadevpur',
  'Manda',
  'Niamatpur',
  'Atrai',
  'Raninagar',
  'Patnitala',
  'Dhamoirhat',
  'Sapahar',
  'Porsha',
  'Badalgachhi',
  'Bagatipara',
  'Lalpur',
  'Natore Sadar',
  'Baraigram',
  'Bholahat',
  'Gomastapur',
  'Nachole',
  'Nawabganj Sadar',
  'Atgharia',
  'Bera',
  'Bhangura',
  'Chatmohar',
  'Faridpur',
  'Ishwardi',
  'Pabna Sadar',
  'Santhia',
  'Sujanagar',
  'Bagha',
  'Bagmara',
  'Charghat',
  'Durgapur',
  'Godagari',
  'Mohanpur',
  'Paba',
  'Puthia',
  'Tanore',
  'Sirajganj Sadar',
  'Belkuchi',
  'Chauhali',
  'Kamarkhanda',
  'Kazipur',
  'Raiganj',
  'Shahjadpur',
  'Tarash',
  'Ullahpara',
  'Birampur',
  'Birganj',
  'Biral',
  'Bochaganj',
  'Chirirbandar',
  'Ghoraghat',
  'Hakimpur',
  'Kaharole',
  'Khansama',
  'Dinajpur Sadar',
  'Parbatipur',
  'Fulchhari',
  'Gaibandha sadar',
  'Gobindaganj',
  'Palashbari',
  'Sadullapur',
  'Saghata',
  'Sundarganj',
  'Kurigram Sadar',
  'Nageshwari',
  'Bhurungamari',
  'Phulbari',
  'Rajarhat',
  'Ulipur',
  'Chilmari',
  'Rowmari',
  'Char Rajibpur',
  'Lalmanirhat Sadar',
  'Aditmari',
  'Hatibandha',
  'Patgram',
  'Nilphamari Sadar',
  'Saidpur',
  'Jaldhaka',
  'Kishoreganj',
  'Domar',
  'Dimla',
  'Panchagarh Sadar',
  'Debiganj',
  'Boda',
  'Atwari',
  'Tetulia',
  'Badarganj',
  'Mithapukur',
  'Gangachara',
  'Kaunia',
  'Rangpur Sadar',
  'Pirgachha',
  'Taraganj',
  'Thakurgaon Sadar',
  'Pirganj',
  'Baliadangi',
  'Haripur',
  'Ranisankail',
  'Ajmiriganj',
  'Baniachang',
  'Bahubal',
  'Chunarughat',
  'Habiganj Sadar',
  'Lakhai',
  'Madhabpur',
  'Nabiganj',
  'Shaistagonj',
  'Moulvibazar Sadar',
  'Barlekha',
  'Juri',
  'Kamalganj',
  'Kulaura',
  'Rajnagar',
  'Sreemangal',
  'Bishwamvarpur',
  'Chhatak',
  'Derai',
  'Dharampasha',
  'Dowarabazar',
  'Jagannathpur',
  'Jamalganj',
  'Sulla',
  'Sunamganj Sadar',
  'Shanthiganj',
  'Tahirpur',
  'Sylhet Sadar',
  'Beanibazar',
  'Bishwanath',
  'Dakshin Surma',
  'Balaganj',
  'Companiganj',
  'Fenchuganj',
  'Golapganj',
  'Gowainghat',
  'Jointapur',
  'Kanaighat',
  'Zakiganj',
  'Nobigonj',
  'Eidgaon',
  'Modhyanagar',
  'Dasar'
]

export const bn_police_stations = () => [
  'আমতলী',
  'বামনা',
  'বরগুনা সদর',
  'বেতাগি',
  'পাথরঘাটা',
  'তালতলী',
  'মুলাদি',
  'বাবুগঞ্জ',
  'আগাইলঝরা',
  'বরিশাল সদর',
  'বাকেরগঞ্জ',
  'বানাড়িপারা',
  'গৌরনদী',
  'হিজলা',
  'মেহেদিগঞ্জ ',
  'ওয়াজিরপুর',
  'ভোলা সদর',
  'বুরহানউদ্দিন',
  'চর ফ্যাশন',
  'দৌলতখান',
  'লালমোহন',
  'মনপুরা',
  'তাজুমুদ্দিন',
  'ঝালকাঠি সদর',
  'কাঁঠালিয়া',
  'নালচিতি',
  'রাজাপুর',
  'বাউফল',
  'দশমিনা',
  'গলাচিপা',
  'কালাপারা',
  'মির্জাগঞ্জ ',
  'পটুয়াখালী সদর',
  'ডুমকি',
  'রাঙ্গাবালি',
  'ভ্যান্ডারিয়া',
  'মাঠবাড়িয়া',
  'নাজিরপুর',
  'নেসারাবাদ',
  'পিরোজপুর সদর',
  'জিয়ানগর',
  'বান্দরবন সদর',
  'থানচি',
  'লামা',
  'নাইখংছড়ি ',
  'আলী কদম',
  'রউয়াংছড়ি ',
  'রুমা',
  'ব্রাহ্মণবাড়িয়া সদর',
  'আশুগঞ্জ',
  'নাসির নগর',
  'নবীনগর',
  'সরাইল',
  'শাহবাজপুর টাউন',
  'কসবা',
  'আখাউরা',
  'বাঞ্ছারামপুর',
  'বিজয় নগর',
  'চাঁদপুর সদর',
  'ফরিদগঞ্জ',
  'হাইমচর',
  'হাজীগঞ্জ',
  'মতলব উত্তর',
  'মতলব দক্ষিণ',
  'শাহরাস্তি',
  'আনোয়ারা',
  'বাশখালি',
  'বোয়ালখালি',
  'চন্দনাইশ',
  'ফটিকছড়ি',
  'হাঠহাজারী',
  'লোহাগারা',
  'মিরসরাই',
  'পটিয়া',
  'রাঙ্গুনিয়া',
  'রাউজান',
  'সন্দ্বীপ',
  'সাতকানিয়া',
  'সীতাকুণ্ড',
  'বড়ুরা',
  'ব্রাহ্মণপাড়া',
  'বুড়িচং',
  'চান্দিনা',
  'চৌদ্দগ্রাম',
  'দাউদকান্দি',
  'দেবীদ্বার',
  'হোমনা',
  'কুমিল্লা সদর',
  'লাকসাম',
  'মনোহরগঞ্জ',
  'মেঘনা',
  'মুরাদনগর',
  'নাঙ্গালকোট',
  'কুমিল্লা সদর দক্ষিণ',
  'তিতাস',
  'চকরিয়া',
  'কক্স বাজার সদর',
  'কুতুবদিয়া',
  'মহেশখালী',
  'রামু',
  'টেকনাফ',
  'উখিয়া',
  'পেকুয়া',
  'ফেনী সদর',
  'ছাগল নাইয়া',
  'দাগানভিয়া',
  'পরশুরাম',
  'ফুলগাজি',
  'সোনাগাজি',
  'দিঘিনালা ',
  'খাগড়াছড়ি',
  'লক্ষ্মীছড়ি',
  'মহলছড়ি',
  'মানিকছড়ি',
  'মাটিরাঙ্গা',
  'পানছড়ি',
  'রামগড়',
  'লক্ষ্মীপুর সদর',
  'রায়পুর',
  'রামগঞ্জ',
  'রামগতি',
  'কমল নগর',
  'নোয়াখালী সদর',
  'বেগমগঞ্জ',
  'চাটখিল',
  'কোম্পানীগঞ্জ',
  'শেনবাগ',
  'হাতিয়া',
  'কবিরহাট ',
  'সোনাইমুরি',
  'সুবর্ণ চর ',
  'রাঙ্গামাটি সদর',
  'বেলাইছড়ি',
  'বাঘাইছড়ি',
  'বরকল',
  'জুরাইছড়ি',
  'রাজাস্থলি',
  'কাপ্তাই',
  'লাঙ্গাডু',
  'নান্নেরচর ',
  'কাউখালি',
  'ধামরাই',
  'দোহার',
  'কেরানীগঞ্জ',
  'নবাবগঞ্জ',
  'সাভার',
  'ফরিদপুর সদর',
  'বোয়ালমারী',
  'আলফাডাঙ্গা',
  'মধুখালি',
  'ভাঙ্গা',
  'নগরকান্ড',
  'চরভদ্রাসন ',
  'সদরপুর',
  'শালথা',
  'গাজীপুর সদর',
  'কালিয়াকৈর',
  'কাপাসিয়া',
  'শ্রীপুর',
  'টঙ্গি',
  'গোপালগঞ্জ সদর',
  'কাশিয়ানি',
  'কোটালিপাড়া',
  'মুকসুদপুর',
  'টুঙ্গিপাড়া',
  'দেওয়ানগঞ্জ',
  'বকসিগঞ্জ',
  'ইসলামপুর',
  'জামালপুর সদর',
  'মাদারগঞ্জ',
  'মেলানদাহা',
  'সরিষাবাড়ি ',
  'নারুন্দি',
  'অষ্টগ্রাম',
  'বাজিতপুর',
  'ভৈরব',
  'হোসেনপুর ',
  'ইটনা',
  'করিমগঞ্জ',
  'কতিয়াদি',
  'কিশোরগঞ্জ সদর',
  'কুলিয়ারচর',
  'মিঠামাইন',
  'নিকলি',
  'পাকুন্ডা',
  'তাড়াইল',
  'মাদারীপুর সদর',
  'কালকিনি',
  'রাজইর',
  'শিবচর',
  'মানিকগঞ্জ সদর',
  'সিঙ্গাইর',
  'শিবালয়',
  'সাটুরিয়া',
  'হরিরামপুর',
  'ঘিওর',
  'দৌলতপুর',
  'লোহাজং',
  'শ্রীনগর',
  'মুন্সিগঞ্জ সদর',
  'সিরাজদিখান',
  'টঙ্গিবাড়ি',
  'গজারিয়া',
  'ভালুকা',
  'ত্রিশাল',
  'হালুয়াঘাট',
  'মুক্তাগাছা',
  'ধবারুয়া',
  'ফুলবাড়িয়া',
  'গফরগাঁও',
  'গৌরিপুর',
  'ঈশ্বরগঞ্জ',
  'ময়মনসিং সদর',
  'নন্দাইল',
  'ফুলপুর',
  'আড়াইহাজার',
  'সোনারগাঁও',
  'বান্দার',
  'নারায়ানগঞ্জ সদর',
  'রূপগঞ্জ',
  'সিদ্ধিরগঞ্জ',
  'বেলাবো',
  'মনোহরদি',
  'নরসিংদী সদর',
  'পলাশ',
  'শিবপুর',
  'কেন্দুয়া',
  'আটপাড়া',
  'বরহাট্টা',
  'দুর্গাপুর',
  'কলমাকান্দা',
  'মদন',
  'মোহনগঞ্জ',
  'নেত্রকোনা সদর',
  'পূর্বধলা',
  'খালিয়াজুরি',
  'বালিয়াকান্দি',
  'গোয়ালন্দ ঘাট',
  'পাংশা',
  'কালুখালি',
  'রাজবাড়ি সদর',
  'শরীয়তপুর সদর ',
  'দামুদিয়া',
  'নড়িয়া',
  'জাজিরা',
  'ভেদারগঞ্জ',
  'গোসাইর হাট ',
  'ঝিনাইগাতি',
  'নাকলা',
  'নালিতাবাড়ি',
  'শেরপুর সদর',
  'শ্রীবরদি',
  'টাঙ্গাইল সদর',
  'সখিপুর',
  'বসাইল',
  'মধুপুর',
  'ঘাটাইল',
  'কালিহাতি',
  'নগরপুর',
  'মির্জাপুর',
  'গোপালপুর',
  'দেলদুয়ার',
  'ভুয়াপুর',
  'ধানবাড়ি',
  'বাগেরহাট সদর',
  'চিতলমাড়ি',
  'ফকিরহাট',
  'কচুয়া',
  'মোল্লাহাট ',
  'মংলা',
  'মরেলগঞ্জ',
  'রামপাল',
  'স্মরণখোলা',
  'দামুরহুদা',
  'চুয়াডাঙ্গা সদর',
  'জীবন নগর ',
  'আলমডাঙ্গা',
  'অভয়নগর',
  'কেশবপুর',
  'বাঘের পাড়া ',
  'যশোর সদর',
  'চৌগাছা',
  'মনিরামপুর ',
  'ঝিকরগাছা',
  'সারশা',
  'ঝিনাইদহ সদর',
  'মহেশপুর',
  'কোট চাঁদপুর ',
  'শৈলকুপা',
  'হাড়িনাকুন্দা',
  'তেরোখাদা',
  'বাটিয়াঘাটা ',
  'ডাকপে',
  'ডুমুরিয়া',
  'দিঘলিয়া',
  'কয়ড়া',
  'পাইকগাছা',
  'ফুলতলা',
  'রূপসা',
  'কুষ্টিয়া সদর',
  'কুমারখালি',
  'মিরপুর',
  'ভেরামারা',
  'খোকসা',
  'মাগুরা সদর',
  'মোহাম্মাদপুর',
  'শালিখা',
  'আংনি',
  'মুজিব নগর',
  'মেহেরপুর সদর',
  'নড়াইল সদর',
  'লোহাগাড়া',
  'কালিয়া',
  'সাতক্ষীরা সদর',
  'আসসাশুনি ',
  'দেভাটা',
  'তালা',
  'কলরোয়া',
  'কালীগঞ্জ',
  'শ্যামনগর',
  'আদমদিঘী',
  'বগুড়া সদর',
  'শেরপুর',
  'ধুনট',
  'দুপচাচিয়া',
  'গাবতলি',
  'কাহালু',
  'নন্দিগ্রাম',
  'শাহজাহানপুর',
  'সারিয়াকান্দি',
  'সোনাতলা',
  'জয়পুরহাট সদর',
  'আক্কেলপুর',
  'কালাই',
  'খেতলাল',
  'পাঁচবিবি',
  'নওগাঁ সদর',
  'মহাদেবপুর',
  'মান্দা',
  'নিয়ামতপুর',
  'আত্রাই',
  'রাণীনগর',
  'পত্নীতলা',
  'ধামইরহাট ',
  'সাপাহার',
  'পোরশা',
  'বদলগাছি',
  'নাটোর সদর',
  'বড়াইগ্রাম',
  'বাগাতিপাড়া',
  'লালপুর',
  'বড়াই গ্রাম',
  'ভোলাহাট',
  'গোমস্তাপুর',
  'নাচোল',
  'নবাবগঞ্জ সদর',
  'শিবগঞ্জ',
  'আটঘরিয়া',
  'বেড়া',
  'ভাঙ্গুরা',
  'চাটমোহর',
  'ফরিদপুর',
  'ঈশ্বরদী',
  'পাবনা সদর',
  'সাথিয়া',
  'সুজানগর',
  'বাঘা',
  'বাগমারা',
  'চারঘাট',
  'গোদাগারি',
  'মোহনপুর',
  'পবা',
  'পুঠিয়া',
  'তানোর',
  'সিরাজগঞ্জ সদর',
  'বেলকুচি',
  'চৌহালি',
  'কামারখান্দা',
  'কাজীপুর',
  'রায়গঞ্জ',
  'শাহজাদপুর',
  'তারাশ',
  'উল্লাপাড়া',
  'বিরামপুর',
  'বীরগঞ্জ',
  'বিড়াল',
  'বোচাগঞ্জ',
  'চিরিরবন্দর',
  'ঘোড়াঘাট',
  'হাকিমপুর',
  'কাহারোল',
  'খানসামা',
  'দিনাজপুর সদর',
  'পার্বতীপুর',
  'ফুলছড়ি',
  'গাইবান্ধা সদর',
  'গোবিন্দগঞ্জ',
  'পলাশবাড়ী',
  'সাদুল্যাপুর',
  'সাঘাটা',
  'সুন্দরগঞ্জ',
  'কুড়িগ্রাম সদর',
  'নাগেশ্বরী',
  'ভুরুঙ্গামারি',
  'ফুলবাড়ি',
  'রাজারহাট',
  'উলিপুর',
  'চিলমারি',
  'রউমারি',
  'চর রাজিবপুর',
  'লালমনিরহাট সদর',
  'আদিতমারি',
  'হাতিবান্ধা',
  'পাটগ্রাম',
  'নীলফামারী সদর',
  'সৈয়দপুর',
  'জলঢাকা',
  'কিশোরগঞ্জ',
  'ডোমার',
  'ডিমলা',
  'পঞ্চগড় সদর',
  'দেবীগঞ্জ',
  'বোদা',
  'আটোয়ারি',
  'তেঁতুলিয়া',
  'বদরগঞ্জ',
  'মিঠাপুকুর',
  'গঙ্গাচরা',
  'কাউনিয়া',
  'রংপুর সদর',
  'পীরগাছা',
  'তারাগঞ্জ',
  'ঠাকুরগাঁও সদর',
  'পীরগঞ্জ',
  'বালিয়াডাঙ্গি',
  'হরিপুর',
  'রাণীসংকইল',
  'আজমিরিগঞ্জ',
  'বানিয়াচং',
  'বাহুবল',
  'চুনারুঘাট',
  'হবিগঞ্জ সদর',
  'লাক্ষাই',
  'মাধবপুর',
  'নবীগঞ্জ',
  'শায়েস্তাগঞ্জ',
  'মৌলভীবাজার',
  'বড়লেখা',
  'জুড়ি',
  'কামালগঞ্জ',
  'কুলাউরা',
  'রাজনগর',
  'শ্রীমঙ্গল',
  'বিসশম্ভারপুর',
  'ছাতক',
  'দেড়াই',
  'ধরমপাশা',
  'দোয়ারাবাজার',
  'জগন্নাথপুর',
  'জামালগঞ্জ',
  'সুল্লা',
  'সুনামগঞ্জ সদর',
  'শান্তিগঞ্জ',
  'তাহিরপুর',
  'সিলেট সদর',
  'বেয়ানিবাজার',
  'বিশ্বনাথ',
  'দক্ষিণ সুরমা',
  'বালাগঞ্জ',
  'কোম্পানিগঞ্জ',
  'ফেঞ্চুগঞ্জ',
  'গোলাপগঞ্জ',
  'গোয়াইনঘাট',
  'জৈন্তাপুর',
  'কানাইঘাট',
  'জাকিগঞ্জ',
  'ঈদগাঁও',
  'মধ্যনগর',
  'দশর'
]
